### ISSUE TITLE
Update Cortex config with correct Prometheus image

### ISSUE THREAD

**Issue by pidster** [microservices-demo/microservices-demo#382]
Prometheus 1.2 upwards will work.

**Comment by jml** [comment]
Note that there's a change in config format between the current version used in sockshop & 1.2. @errordeveloper was hurt by that earlier this week.

Fix is to be sure that `remote_write` is a single value (example below), not a list [as it is now](https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/manifests-cortex/cortex-config.yaml#L11).

``` yaml
    remote_write:
      url: https://cloud.weave.works:443/api/prom/push
      basic_auth:
        password: WEAVE_CLOUD_TOKEN
      tls_config:
        insecure_skip_verify: true
```
