### ISSUE TITLE
How to trace more services? [Jaeger]

### ISSUE THREAD

**Issue by open-richard** [microservices-demo/microservices-demo#769]
Hi,

I am completely new to the microservices and tracing world. And I find that I am a little bit lost in adding a new monitored service in the Jaeger UI. Tons of different opensource projects suddently come at a time playing with this microservices-demo project which is cool, but the documentation seems to be a little bit lag behind (or inconsistent with the code) which I would love to help if things work out.
I deployed a multi-node kubernetes cluster and run the `kubectl apply -f complete-demo.yaml` to create a sockshop.
And then I run the `kubectl apply -f ./manifests-jaeger`. Then I can see 4 Services in the drop-down list of the Jaeger UI. But I failed to show the dependency graph neither tracing other services.

I tried to make a new yaml to apply like attached in the bottom. But the `front-end` service can not be seen in the Jaeger UI Service drop-down list.

Can anyone kindly give some hints on what I should try or provide a link for me to learn how to trace all the services?

Thank you very much in advance.

Attached is a screenshot and the front-end yaml file I tried but fail.
![jaeger-only-show-4-services](https://user-images.githubusercontent.com/8740357/41824629-5caa31c0-77e1-11e8-94cc-07e0686dd934.png)

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-end
  namespace: sock-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: front-end
        image: weaveworksdemos/front-end:0.3.12
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: ZIPKIN
          value: http://zipkin.jaeger.svc.cluster.local:9411/api/v1/spans
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8079
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 180
          periodSeconds: 3
      nodeSelector:
        beta.kubernetes.io/os: linux
```
