### ISSUE TITLE
Sockshop in istio perform error

### ISSUE THREAD

**Issue by yuxiaoba** [microservices-demo/microservices-demo#782]
I user the commad
`kubectl apply -f <(istioctl kube-inject -f complete-demo.yaml)`
I could get this
root@R740-2-1:~/istio-1.0.0/sockshop# kubectl get pod -n sock-shop 
```
NAME                            READY     STATUS    RESTARTS   AGE
carts-6ccf5f57fb-844p4          2/2       Running   0          3d
carts-db-6b8fb6bf94-2zsvk       2/2       Running   0          3d
catalogue-58dc6f6886-zzzzx      2/2       Running   0          6h
catalogue-db-7c68599b85-8ctnf   2/2       Running   0          3d
front-end-5ccb774864-l69p4      2/2       Running   1          10h
orders-6dbbb9f98b-g8v99         2/2       Running   0          3d
orders-db-ccdb77dcb-j8zhz       2/2       Running   0          3d
payment-7c6c9d7457-2jsdw        2/2       Running   0          3d
queue-master-6f866bb8c-dxgf8    2/2       Running   0          3d
rabbitmq-759fbc775f-td6rl       2/2       Running   2          3d
shipping-5cdc7566df-kmbn6       2/2       Running   0          3d
user-7bffd9566-pqv8h            2/2       Running   0          3d
user-db-86844cfdd-jjq2j         2/2       Running   0          3d
```

root@R740-2-1:~/istio-1.0.0/sockshop# kubectl get svc -n sock-shop
```
NAME           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
carts          ClusterIP   10.68.204.30    <none>        80/TCP              3d
carts-db       ClusterIP   10.68.226.250   <none>        27017/TCP           3d
catalogue      ClusterIP   10.68.214.230   <none>        80/TCP              3d
catalogue-db   ClusterIP   10.68.11.236    <none>        3306/TCP            3d
front-end      ClusterIP   10.68.127.50    <none>        80/TCP              3d
orders         ClusterIP   10.68.194.14    <none>        80/TCP              3d
orders-db      ClusterIP   10.68.57.167    <none>        27017/TCP           3d
payment        ClusterIP   10.68.134.203   <none>        80/TCP              3d
queue-master   ClusterIP   10.68.126.95    <none>        80/TCP              3d
rabbitmq       ClusterIP   10.68.82.238    <none>        5672/TCP,4369/TCP   3d
shipping       ClusterIP   10.68.129.250   <none>        80/TCP              3d
user           ClusterIP   10.68.92.184    <none>        80/TCP              3d
user-db        ClusterIP   10.68.188.116   <none>        27017/TCP           3d
```

And I write a ingressgateway for sockshop
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sockshop-gateway
  namespace: sock-shop
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sockshop
  namespace: sock-shop
spec:
  hosts:
  - "*"
  gateways:
  - sockshop-gateway
  http:
  - match:
     - uri:
         exact: /
    route:
    - destination:
        host: front-end
        port:
          number: 80
```
But I only can get front-end data in grafana when I loadtest sock-shop
Not like the bookinfo services, I can see all the service'data in garfana

**Comment by fjudith** [comment]
Hello,

If remember well. Bookinfo is published in the `default` namespace.
I assume then that you already have deployed the gateway in this namespace.

As you can publish only one gateway for a given port, you should publish your vitualservice in the `default` namespace with the appropriates gateway name and host fully qualified name (i.e. `front-end.sock-shop.svc.cluster.local`)

I recommend you to change the label `name:` by `app:` in the sock-shop manifests to get appropriate metric in Istio Prometheus instance.

**Comment by fjudith** [comment]
/close

This is not a sock-shop issue

**Comment by JackGzj** [comment]
> I user the commad
> `kubectl apply -f <(istioctl kube-inject -f complete-demo.yaml)`
> I could get this
> root@R740-2-1:~/istio-1.0.0/sockshop# kubectl get pod -n sock-shop
> NAME READY STATUS RESTARTS AGE
> carts-6ccf5f57fb-844p4 2/2 Running 0 3d
> carts-db-6b8fb6bf94-2zsvk 2/2 Running 0 3d
> catalogue-58dc6f6886-zzzzx 2/2 Running 0 6h
> catalogue-db-7c68599b85-8ctnf 2/2 Running 0 3d
> front-end-5ccb774864-l69p4 2/2 Running 1 10h
> orders-6dbbb9f98b-g8v99 2/2 Running 0 3d
> orders-db-ccdb77dcb-j8zhz 2/2 Running 0 3d
> payment-7c6c9d7457-2jsdw 2/2 Running 0 3d
> queue-master-6f866bb8c-dxgf8 2/2 Running 0 3d
> rabbitmq-759fbc775f-td6rl 2/2 Running 2 3d
> shipping-5cdc7566df-kmbn6 2/2 Running 0 3d
> user-7bffd9566-pqv8h 2/2 Running 0 3d
> user-db-86844cfdd-jjq2j 2/2 Running 0 3d
> 
> root@R740-2-1:~/istio-1.0.0/sockshop# kubectl get svc -n sock-shop
> NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
> carts ClusterIP 10.68.204.30 80/TCP 3d
> carts-db ClusterIP 10.68.226.250 27017/TCP 3d
> catalogue ClusterIP 10.68.214.230 80/TCP 3d
> catalogue-db ClusterIP 10.68.11.236 3306/TCP 3d
> front-end ClusterIP 10.68.127.50 80/TCP 3d
> orders ClusterIP 10.68.194.14 80/TCP 3d
> orders-db ClusterIP 10.68.57.167 27017/TCP 3d
> payment ClusterIP 10.68.134.203 80/TCP 3d
> queue-master ClusterIP 10.68.126.95 80/TCP 3d
> rabbitmq ClusterIP 10.68.82.238 5672/TCP,4369/TCP 3d
> shipping ClusterIP 10.68.129.250 80/TCP 3d
> user ClusterIP 10.68.92.184 80/TCP 3d
> user-db ClusterIP 10.68.188.116 27017/TCP 3d
> 
> And I write a ingressgateway for sockshop
> `apiVersion: networking.istio.io/v1alpha3
> kind: Gateway
> metadata:
> name: sockshop-gateway
> namespace: sock-shop
> spec:
> selector:
> istio: ingressgateway # use istio default controller
> servers:
> 
> * port:
>   number: 80
>   name: http
>   protocol: HTTP
>   hosts:
>   
>   * "*"
> 
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
> name: sockshop
> namespace: sock-shop
> spec:
> hosts:
> 
> * "*"
>   gateways:
> * sockshop-gateway
>   http:
> * match:
>   
>   * uri:
>     exact: /
>     route:
>   * destination:
>     host: front-end
>     port:
>     number: 80
>     `
>     But I only can get front-end data in grafana when I loadtest sock-shop
>     Not like the bookinfo services, I can see all the service'data in garfana

Hello, I am deploying sock-shop on istio, but I got the rabbitmq error and keep restarting. My istio version is 1.0.0 and the rabbitmq image tag is 3.6.8.

**Comment by fjudith** [comment]
@JackGzj 

Simply add the epmd port to the rabbitmq deployment and services.

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 5672
    name: rabbitmq
    targetPort: 5672
  - port: 4369
    name: epmd
  - port: 9090
    name: exporter
    targetPort: exporter
    protocol: TCP
  selector:
    app: rabbitmq
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
  namespace: sock-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.6.8-management
        ports:
        - containerPort: 15672
          name: management
        - containerPort: 5672
          name: rabbitmq
        - containerPort: 4369
          name: epmd
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
              - DAC_OVERRIDE
          readOnlyRootFilesystem: true
      - name: rabbitmq-exporter
        image: kbudde/rabbitmq-exporter
        ports:
        - containerPort: 9090
          name: exporter
      nodeSelector:
        beta.kubernetes.io/os: linux
```

**Comment by JackGzj** [comment]
> epmd

Get it, thank you very much.

**Comment by JackGzj** [comment]
> @JackGzj
> 
> Simply add the epmd port to the rabbitmq deployment and services.
> 
> ```yaml
> ---
> apiVersion: v1
> kind: Service
> metadata:
>   name: rabbitmq
>   labels:
>     app: rabbitmq
>   namespace: sock-shop
> spec:
>   ports:
>     # the port that this service should serve on
>   - port: 5672
>     name: rabbitmq
>     targetPort: 5672
>   - port: 4369
>     name: epmd
>   - port: 9090
>     name: exporter
>     targetPort: exporter
>     protocol: TCP
>   selector:
>     app: rabbitmq
> ---
> apiVersion: extensions/v1beta1
> kind: Deployment
> metadata:
>   name: rabbitmq
>   labels:
>     app: rabbitmq
>   namespace: sock-shop
> spec:
>   replicas: 1
>   template:
>     metadata:
>       labels:
>         app: rabbitmq
>       annotations:
>         prometheus.io/scrape: "false"
>     spec:
>       containers:
>       - name: rabbitmq
>         image: rabbitmq:3.6.8-management
>         ports:
>         - containerPort: 15672
>           name: management
>         - containerPort: 5672
>           name: rabbitmq
>         - containerPort: 4369
>           name: epmd
>         securityContext:
>           capabilities:
>             drop:
>               - all
>             add:
>               - CHOWN
>               - SETGID
>               - SETUID
>               - DAC_OVERRIDE
>           readOnlyRootFilesystem: true
>       - name: rabbitmq-exporter
>         image: kbudde/rabbitmq-exporter
>         ports:
>         - containerPort: 9090
>           name: exporter
>       nodeSelector:
>         beta.kubernetes.io/os: linux
> ```
Here is another problem that, I set the gateway as it's set in this PR but I could't visit the front-end through ingressgateway. Do I miss any configuration?

**Comment by hechuan73** [comment]
@JackGzj 
Maybe you can try to set the gateway such as:
```
http:
  - match:
    - uri:
        prefix: /
```
use "prefix" instead of "exact", and then visit the front-end.
